include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - backup/**
    - apps/**/test/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
